# After change this file needs to restart sidekiq
daily_mailing:
  # Minute(0-59) Hour(0-23) DayOfMonth(0-31) Month(0-12) DayOfWeek(0-6) / - step
  cron: "0 7 * * * Europe/Moscow"
  # for test purposes uncomment the next line - will mail every minute
  # cron: '* * * * *'
  class: "DailyMailingWorker"
  queue: default

weekly_mailing:
  # Minute(0-59) Hour(0-23) DayOfMonth(0-31) Month(0-12) DayOfWeek(0-6) / - step
  cron: "0 7 * * 1 Europe/Moscow"
  # for test purposes uncomment the next line - will mail every 5 minutes
  # cron: '*/2 * * * *'
  class: "WeeklyMailingWorker"
  queue: default
