daily_mailing:
  # Minute(0-59) Hour(0-23) DayOfMonth(0-31) Month(0-12) DayOfWeek(0-6)
  cron: "0 7 * * *"
  class: "DailyMailingJob"
  queue: default

weekly_mailing:
  # Minute(0-59) Hour(0-23) DayOfMonth(0-31) Month(0-12) DayOfWeek(0-6)
  cron: "0 7 * * 1"
  class: "WeeklyMailingJob"
  queue: default
